export const mockData = [
  {
    id: 1,
    currentTeam: 'ซาคราเมนโต คิงส์',
    defeatTeam: 'มินนิโซตา ทิมเบอร์วูล์ฟส์',
    currentTeamLogo: require('@assets/image/icon2.png'),
    defeatTeamLogo: require('@assets/image/icon1.png'),
    competitions: [
      {name: 'Q1'},
      {name: 'Q2'},
      {name: 'BR'},
      {name: 'Q3'},
      {name: 'Q4'},
      {name: 'FN'},
    ],
    rounds: [
      {name: '1', isWin: false},
      {name: '2', isWin: true},
      {name: '3', isWin: false},
      {name: '4', isWin: true},
      {name: '5', isWin: false},
      {name: '6', isWin: false},
    ],
  },
  {
    id: 2,
    currentTeam: 'บอสตัน เซลติกส์',
    defeatTeam: 'ชิคาโก บูลส์',
    currentTeamLogo: require('@assets/image/icon2.png'),
    defeatTeamLogo: require('@assets/image/icon1.png'),
    competitions: [
      {name: 'Q1'},
      {name: 'Q2'},
      {name: 'BR'},
      {name: 'Q3'},
      {name: 'Q4'},
      {name: 'FN'},
    ],
    rounds: [
      {name: '1', isWin: true},
      {name: '2', isWin: true},
      {name: '3', isWin: true},
      {name: '4', isWin: false},
      {name: '5', isWin: true},
      {name: '6', isWin: false},
    ],
  },
  {
    id: 3,
    currentTeam: 'ลอสแอนเจลิส เลเกอร์ส',
    defeatTeam: 'ฟีนิกซ์ ซันส์',
    currentTeamLogo: require('@assets/image/icon2.png'),
    defeatTeamLogo: require('@assets/image/icon1.png'),
    competitions: [
      {name: 'Q1'},
      {name: 'Q2'},
      {name: 'BR'},
      {name: 'Q3'},
      {name: 'Q4'},
      {name: 'FN'},
    ],
    rounds: [
      {name: '1', isWin: true},
      {name: '2', isWin: true},
      {name: '3', isWin: false},
      {name: '4', isWin: true},
      {name: '5', isWin: false},
      {name: '6', isWin: false},
    ],
  },
  {
    id: 4,
    currentTeam: 'ไมอามี ฮีต',
    defeatTeam: 'ดีทรอยต์ พิสตันส์',
    currentTeamLogo: require('@assets/image/icon2.png'),
    defeatTeamLogo: require('@assets/image/icon1.png'),
    competitions: [
      {name: 'Q1'},
      {name: 'Q2'},
      {name: 'BR'},
      {name: 'Q3'},
      {name: 'Q4'},
      {name: 'FN'},
    ],
    rounds: [
      {name: '1', isWin: false},
      {name: '2', isWin: false},
      {name: '3', isWin: true},
      {name: '4', isWin: true},
      {name: '5', isWin: false},
      {name: '6', isWin: true},
    ],
  },
  {
    id: 5,
    currentTeam: 'โกลเด้น สเตท วอร์ริเออร์ส',
    defeatTeam: 'ฮิวสตัน ร็อคเก็ตส์',
    currentTeamLogo: require('@assets/image/icon2.png'),
    defeatTeamLogo: require('@assets/image/icon1.png'),
    competitions: [
      {name: 'Q1'},
      {name: 'Q2'},
      {name: 'BR'},
      {name: 'Q3'},
      {name: 'Q4'},
      {name: 'FN'},
    ],
    rounds: [
      {name: '1', isWin: true},
      {name: '2', isWin: false},
      {name: '3', isWin: false},
      {name: '4', isWin: true},
      {name: '5', isWin: true},
      {name: '6', isWin: false},
    ],
  },
  {
    id: 6,
    currentTeam: 'ฟิลาเดลเฟีย 76เซอร์ส',
    defeatTeam: 'อินเดียนา เพเซอร์ส',
    currentTeamLogo: require('@assets/image/icon2.png'),
    defeatTeamLogo: require('@assets/image/icon1.png'),
    competitions: [
      {name: 'Q1'},
      {name: 'Q2'},
      {name: 'BR'},
      {name: 'Q3'},
      {name: 'Q4'},
      {name: 'FN'},
    ],
    rounds: [
      {name: '1', isWin: false},
      {name: '2', isWin: true},
      {name: '3', isWin: false},
      {name: '4', isWin: false},
      {name: '5', isWin: true},
      {name: '6', isWin: true},
    ],
  },
  {
    id: 7,
    currentTeam: 'เดนเวอร์ นักเก็ตส์',
    defeatTeam: 'โอคลาโฮมา ซิตี้ ธันเดอร์',
    currentTeamLogo: require('@assets/image/icon2.png'),
    defeatTeamLogo: require('@assets/image/icon1.png'),
    competitions: [
      {name: 'Q1'},
      {name: 'Q2'},
      {name: 'BR'},
      {name: 'Q3'},
      {name: 'Q4'},
      {name: 'FN'},
    ],
    rounds: [
      {name: '1', isWin: true},
      {name: '2', isWin: false},
      {name: '3', isWin: true},
      {name: '4', isWin: false},
      {name: '5', isWin: true},
      {name: '6', isWin: true},
    ],
  },
  {
    id: 8,
    currentTeam: 'โอกแลนด์ วอร์ริเออร์ส',
    defeatTeam: 'ชิคาโก บูลส์',
    currentTeamLogo: require('@assets/image/icon2.png'),
    defeatTeamLogo: require('@assets/image/icon1.png'),
    competitions: [
      {name: 'Q1'},
      {name: 'Q2'},
      {name: 'BR'},
      {name: 'Q3'},
      {name: 'Q4'},
      {name: 'FN'},
    ],
    rounds: [
      {name: '1', isWin: true},
      {name: '2', isWin: false},
      {name: '3', isWin: true},
      {name: '4', isWin: true},
      {name: '5', isWin: false},
      {name: '6', isWin: true},
    ],
  },
  {
    id: 9,
    currentTeam: 'คลีฟแลนด์ คาวาเลียร์ส',
    defeatTeam: 'บรู๊คลิน เน็ตส์',
    currentTeamLogo: require('@assets/image/icon2.png'),
    defeatTeamLogo: require('@assets/image/icon1.png'),
    competitions: [
      {name: 'Q1'},
      {name: 'Q2'},
      {name: 'BR'},
      {name: 'Q3'},
      {name: 'Q4'},
      {name: 'FN'},
    ],
    rounds: [
      {name: '1', isWin: false},
      {name: '2', isWin: true},
      {name: '3', isWin: true},
      {name: '4', isWin: false},
      {name: '5', isWin: true},
      {name: '6', isWin: false},
    ],
  },
  {
    id: 10,
    currentTeam: 'แอตแลนต้า ฮอว์กส์',
    defeatTeam: 'ยูทาห์ แจซ',
    currentTeamLogo: require('@assets/image/icon2.png'),
    defeatTeamLogo: require('@assets/image/icon1.png'),
    competitions: [
      {name: 'Q1'},
      {name: 'Q2'},
      {name: 'BR'},
      {name: 'Q3'},
      {name: 'Q4'},
      {name: 'FN'},
    ],
    rounds: [
      {name: '1', isWin: true},
      {name: '2', isWin: false},
      {name: '3', isWin: true},
      {name: '4', isWin: false},
      {name: '5', isWin: true},
      {name: '6', isWin: true},
    ],
  },
];
